import fs from 'node:fs/promises';
import path from 'node:path';
import { ROOT, assert, atomicJSON, contained, exists, git, readJSON, sha } from './io.mjs';
import { ACCESS, CONFIG_VERSION, defaultConfig, validateConfig } from './config.mjs';

export async function initWorkspace({ workspace, project, profile = 'generic', vault = null, url = 'https://github.com/ParkPavel/claudex', access = 'approval', assignments = {}, models = {}, executables = {} }) {
  const root = await fs.realpath(path.resolve(workspace));
  const target = await contained(root, path.resolve(root, project));
  assert(target !== root, 'The desktop root must contain the managed project, not be the project');
  assert(target !== ROOT, 'The harness and managed project must be distinct repositories');
  assert(path.resolve((await git(target, ['rev-parse', '--show-toplevel'])).trim()) === target, 'Project is not a Git root');
  assert(/^[a-z][a-z0-9-]*$/.test(profile) && await exists(path.join(ROOT, 'profiles', `${profile}.json`)), 'Unknown profile');
  const state = path.join(root, '.local', 'claudex');
  await fs.mkdir(state, { recursive: true });
  const configPath = path.join(state, 'workspace.json');
  assert(!(await exists(configPath)), 'Workspace already exists. Use sync to update generated entrypoints.');
  assert(ACCESS.includes(access), `Unknown access mode ${access}; expected ${ACCESS.join(', ')}`);
  const config = defaultConfig({ project: path.relative(root, target), profile, vault, url });
  config.access = access;
  config.assignments = assignments;
  config.models = { ...config.models, ...models };
  config.executables = { ...config.executables, ...executables };
  validateConfig(config, await readJSON(path.join(ROOT, 'config/roles.json')));
  await atomicJSON(configPath, config);
  await atomicJSON(path.join(root, '.claudex.json'), { schemaVersion: 1, state: '.local/claudex' });
  await fs.mkdir(path.join(root, '.tmp'), { recursive: true });
  const ws = { root, state, project: target, config };
  await syncWorkspace(ws);
  return ws;
}
export async function syncWorkspace(ws) {
  // Reading a workspace migrates its configuration in memory; this is where the
  // upgrade is written down, once, next to the generated files it belongs with.
  if (ws.storedVersion !== undefined && ws.storedVersion !== CONFIG_VERSION) {
    await atomicJSON(path.join(ws.state, 'workspace.json'), ws.config);
  }
  const manifestPath = path.join(ws.state, 'generated-files.json');
  const previous = await exists(manifestPath) ? await readJSON(manifestPath) : {};
  const files = {};
  const relHarness = path.relative(ws.root, ROOT).split(path.sep).join('/');
  const pointer = `# Claudex workspace\n\nAgent configuration moved to [Claudex](${ws.config.repositoryUrl}).\nRead [the shared contract](${relHarness}/config/core.md) before work.\nManaged project: \`${ws.config.project}\`. Local context: \`.local/claudex/project-profile.md\` when present.\nRun \`node ${relHarness}/bin/claudex.mjs doctor\` to verify this workspace.\nUse \`node ${relHarness}/bin/claudex.mjs\` for jobs and Obsidian CLI evidence.\nLoad relevant skills from \`${relHarness}/skills\`; do not load the full library by default.\n`;
  files['AGENTS.md'] = pointer;
  files['CLAUDE.md'] = pointer;
  files['.gitignore'] = '# This desktop is local storage. Publish each nested repository independently.\n*\n';
  files['.codex/config.toml'] = '# Generated by Claudex. Shared policy and roles are maintained in the harness repository.\nsandbox_mode = "read-only"\napproval_policy = "never"\n';
  files['.claude/settings.json'] = JSON.stringify({ permissions: { deny: ['Bash(git push --force*)', 'Bash(git push -f*)', 'Bash(git reset --hard*)', 'Bash(git clean*)'] } }, null, 2) + '\n';
  const roles = await readJSON(path.join(ROOT, 'config/roles.json'));
  for (const [name, role] of Object.entries(roles)) {
    const text = `${role.purpose}\nRead ${path.join(ROOT, 'config/core.md').split(path.sep).join('/')} and the selected project profile. Use Claudex jobs for delegated work. Skill names: ${role.skills.join(', ')}.\n`;
    if (role.provider === 'claude') files[`.claude/agents/${name}.md`] = `---\nname: ${name}\ndescription: ${JSON.stringify(role.purpose)}\nmodel: ${role.model}\neffort: ${role.effort}\ntools: Read, Glob, Grep${role.authority === 'workspace-write' ? ', Edit, Write' : ''}\n---\n${text}`;
    else files[`.codex/agents/${name}.toml`] = `name = ${JSON.stringify(name)}\ndescription = ${JSON.stringify(role.purpose)}\nsandbox_mode = "read-only"\nmodel_reasoning_effort = ${JSON.stringify(role.effort)}\ndeveloper_instructions = ${JSON.stringify(text)}\n`;
  }
  // Native discovery needs small SKILL.md files at each host's supported path.
  // They point to a single maintained body instead of copying that body twice.
  for (const skill of await fs.readdir(path.join(ROOT, 'skills'))) {
    const body = await fs.readFile(path.join(ROOT, 'skills', skill, 'SKILL.md'), 'utf8');
    const front = body.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    assert(front, `Missing frontmatter for ${skill}`);
    const stub = `---\n${front[1]}\n---\nRead and follow the maintained skill at ${path.join(ROOT, 'skills', skill, 'SKILL.md').split(path.sep).join('/')} for this task.\n`;
    files[`.agents/skills/${skill}/SKILL.md`] = stub;
    files[`.claude/skills/${skill}/SKILL.md`] = stub;
  }
  const manifest = {};
  const retired = [];
  for (const rel of Object.keys(previous).filter(rel => !Object.hasOwn(files,rel))) {
    const target = await contained(ws.root,path.join(ws.root,rel));
    if (await exists(target)) {
      assert(sha(await fs.readFile(target)) === previous[rel],`Edited retired entrypoint: ${rel}`);
      retired.push(target);
    }
  }
  for (const [rel, body] of Object.entries(files)) {
    const target = await contained(ws.root, path.join(ws.root, rel));
    if (await exists(target)) {
      const current = await fs.readFile(target);
      assert(sha(current) === previous[rel] || current.toString('utf8') === body, `Unmanaged or edited entrypoint: ${rel}. Back it up before migration.`);
    }
    manifest[rel] = sha(body);
  }
  for (const [rel, body] of Object.entries(files)) {
    const target = path.join(ws.root, rel);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, body, 'utf8');
  }
  for (const target of retired) await fs.unlink(target);
  await atomicJSON(manifestPath, manifest);
  return { files: Object.keys(manifest).length, root: ws.root };
}
export async function checkEntrypoints(ws) {
  const manifest = await readJSON(path.join(ws.state, 'generated-files.json'));
  const drift = [];
  for (const [rel, expected] of Object.entries(manifest)) {
    const file = await contained(ws.root, path.join(ws.root, rel));
    if (!(await exists(file)) || sha(await fs.readFile(file)) !== expected) drift.push(rel);
  }
  return drift;
}
export async function createWorktree(ws, taskId, base = 'HEAD') {
  assert(/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,70}$/.test(taskId), 'Invalid task ID');
  const fullBase = (await git(ws.project, ['rev-parse', '--verify', `${base}^{commit}`])).trim();
  const dir = await contained(ws.root, path.join(ws.state, 'worktrees', taskId));
  await fs.mkdir(path.dirname(dir), { recursive: true });
  await git(ws.project, ['worktree', 'add', '-b', `claudex/${taskId}`, dir, fullBase]);
  const profile = await readJSON(path.join(ROOT, 'profiles', `${ws.config.profile}.json`));
  for (const file of profile.requiredFiles) assert(await exists(path.join(dir, file)), `Worktree is missing ${file}`);
  const pointer = `# Managed by Claudex\n\nRead ${path.join(ROOT, 'config/core.md').split(path.sep).join('/')} and ${path.join(ws.state, 'project-profile.md').split(path.sep).join('/')} when present.\nConfiguration moved to ${ws.config.repositoryUrl}.\n`;
  for (const name of ['AGENTS.md','CLAUDE.md']) {
    const file = path.join(dir, name);
    assert(!(await exists(file)), `Worktree has tracked ${name}; bootstrap must not overwrite it`);
    await fs.writeFile(file, pointer);
  }
  return { path: dir, base: fullBase, branch: `claudex/${taskId}` };
}
